{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atlas.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas.api.labels" . | nindent 4 }}
spec:
  {{- if not (kindIs "invalid" .Values.api.pdb.minAvailable) }}
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atlas.api.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if .Values.worker.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atlas.worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas.worker.labels" . | nindent 4 }}
spec:
  {{- if not (kindIs "invalid" .Values.worker.pdb.minAvailable) }}
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atlas.worker.selectorLabels" . | nindent 6 }}
{{- end }}
